root: true
parser: '@typescript-eslint/parser'
parserOptions:
  jsx: true
  useJSXTextNode: true
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
plugins:
  - '@typescript-eslint'
  - react-hooks
  - no-loops
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
  - plugin:prettier/recommended
rules:
  no-loops/no-loops: warn
  no-console: warn
  prettier/prettier: error
  '@typescript-eslint/explicit-function-return-type': off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  "@typescript-eslint/explicit-module-boundary-types": off
